config/routes.rb
Rails.application.routes.draw do
  get 'practices/index'
  get 'practices/new'
  root to: 'practices#index'
  resources :practices
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lure.rb
class Lure < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: 'スプーン' },
    { id: 3, name: 'ポッパー' },
    { id: 4, name: 'ペンシルベイト' },
    { id: 5, name: 'ノイジー' },
    { id: 6, name: 'スイッシャー' },
    { id: 7, name: 'フローティングミノー' },
    { id: 8, name: 'シンキングミノー' },
    { id: 9, name: 'リップレスミノー' },
    { id: 10, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :practices

  end

app/models/practice.rb
class Practice < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :lure
  has_one_attached :image

  validates :title, presence: true
  validates :text,  presence: true
  validates :image, presence: true

  validates :lure_id, numericality: { other_than: 1 , message: "can't be blank"}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/practices_controller.rb
class PracticesController < ApplicationController

  def index
    @practices = Practice.all.order("created_at DESC")
  end

  def new
    @practice = Practice.new
  end

  def create
    @practice = Practice.new(practice_params)
    if @practice.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def practice_params
    params.require(:practice).permit(:title, :text, :lure_id ,:image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/practices_helper.rb
module PracticesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PracticeApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/practices/_form.html.erb
<%= form_with model: practice, local: true do |f|%>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title, id:"practice_title" %>
  </div>

  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_area :text, class: :form__text, id:"practice_text" %>
  </div>

<div class="field">
    <%= f.label :lure %><br />
    <%= f.collection_select(:lure_id, Lure.all, :id, :name, {}, {class:"lure-select"}) %>
    </div>

  <div class="field">
    <%= f.file_field :image %><br />
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/practices/_practice.html.erb
<div class="card__wrapper">
      <%# 投稿機能実装後、部分テンプレートでプロトタイプ投稿一覧を表示する %>
        <%= render partial: 'practice', collection: @practice %>
    </div>

app/views/practices/index.html.erb
<h1>魚の投稿の一覧</h1>
<%= link_to "投稿する", new_practice_path, class:"post" %>

<% @practices.each do |practice| %>
  <div class="practice">
    <div class="practice-lure">
    ルアー名
      <%= practice.lure.name %>
    </div>
    <div class="practice-title">
    魚の名前
      <%= practice.title %>
    </div>
    <div class="practice-text">
    場所や感想など
      <%= practice.text %>
    </div>
    <div class="practice-image">
    魚の画像
      <%= image_tag practice.image.variant(resize: '500x500'), class: 'practice-image' if practice.image.attached? %>
    </div>
  </div>
<% end %>

app/views/practices/new.html.erb
<div class="practice-box">
    魚を投稿する
    <%# 部分テンプレートでフォームを表示する %>
    <%= render partial: "form", locals: { practice: @practice } %>
    
  </div>